[repositories]
tedge-rugpi-core = { git = "https://github.com/thin-edge/tedge-rugxi-core.git", branch = "v0.8-rugxi" }
# branch should be v0.8 or v0.8-rugxi????

[images.alpine-amd64]
layer = "alpine-default"
architecture = "amd64"
target = "generic-grub-efi"

[images.debian-amd64]
layer = "debian-default"
architecture = "amd64"
target = "generic-grub-efi"

# This image has a larger size and can be directly used with QEMU.
[images.debian-amd64-vm]
layer = "debian-default"
architecture = "amd64"
target = "generic-grub-efi"
size = "16G"

[images.debian-arm64]
layer = "debian-default"
architecture = "arm64"
target = "generic-grub-efi"

# This image has a larger size and can be directly used with QEMU.
[images.debian-arm64-vm]
layer = "debian-default"
architecture = "arm64"
target = "generic-grub-efi"
size = "16G"

# Image for Raspberry Pi 4, 5, CM4, 400
[images.rpi-tryboot]
layer = "rpi-default"
architecture = "arm64"
target = "rpi-tryboot"

# Image for Raspberry Pi 4, 5, CM4, 400 - includes containerization dependencies
[images.rpi-tryboot-containers]
layer = "rpi-containers"
architecture = "arm64"
target = "rpi-tryboot"

# A specific image including the firmware update for Raspberry Pi 4 and CM4.
[images.rpi-tryboot-pi4]
layer = "rpi-default-pi4"
architecture = "arm64"
target = "rpi-tryboot"

# An image using the U-Boot boot flow for Raspberry Pi 3 and Zero 2.
[images.rpi-u-boot]
layer = "rpi-default"
architecture = "arm64"
target = "rpi-uboot"

# An image using the U-Boot boot flow for Raspberry Pi 3 and Zero 2 with containerization dependencies
[images.rpi-u-boot-containers]
layer = "rpi-containers"
architecture = "arm64"
target = "rpi-uboot"

# An `armhf` image for older Raspberry Pi's using the U-Boot boot flow.
[images.rpi-u-boot-armhf]
layer = "rpi-default"
architecture = "armhf"
target = "rpi-uboot"

[images.rpi-u-boot-armhf-containers]
layer = "rpi-containers"
architecture = "armhf"
target = "rpi-uboot"