parent = "tedge-rugpi-core/tedge-alpine-320"
# Need to add this parent in tedge-rugpi-core repo -- added

recipes = [
    "core/rugpi-ctrl",
    # "tedge-rugpi-core/docker",
    # "tedge-rugpi-core/systemd-resolved",
    # "tedge-rugpi-core/boot-options",
    # "tedge-config",
]
# Need to modify for alpine and podman(optional)

[parameters."core/rugpi-ctrl"]
rugpi_admin = true  # Enable Rugpi Admin.

[parameters."tedge-config"]
# Allow containers to reach the MQTT broker on the host
mqtt_bind_address = "0.0.0.0"